apiVersion: v1
kind: List
items:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: argo-rollouts
      labels:
        type: infrastructure
    spec:
      project: default
      source:
        repoURL: https://github.com/dinushchathurya/argocd/combined-demo.git
        path: argo/argo-rollout
      destination: *dest
      syncPolicy: *policy

  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: minio
      labels:
        type: infrastructure
    spec:
      project: default
      source:
        repoURL: https://github.com/dinushchathurya/argocd/combined-demo.git
        path: application
      destination: *dest
      syncPolicy: *policy

  - apiVersion: v1
    kind: Namespace
    metadata:
      name: demo